/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as PinterestCallbackRouteImport } from './routes/pinterest.callback'
import { Route as AuthenticatedSwitchProfileRouteImport } from './routes/_authenticated/switch-profile'
import { Route as AuthenticatedStorefrontRouteImport } from './routes/_authenticated/storefront'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPinsRouteImport } from './routes/_authenticated/pins'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBrandsRouteImport } from './routes/_authenticated/brands'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedPinsPreviewRouteImport } from './routes/_authenticated/pins_.preview'
import { Route as AuthenticatedPinsMonetizeBoardRouteImport } from './routes/_authenticated/pins_.monetize-board'
import { Route as AuthenticatedPinsCreateRouteImport } from './routes/_authenticated/pins_.create'
import { Route as AuthenticatedPinsAttachRouteImport } from './routes/_authenticated/pins_.attach'
import { Route as AuthenticatedBrandsBrandIdRouteImport } from './routes/_authenticated/brands_.$brandId'
import { Route as AuthenticatedCollectionsIdAttachRouteImport } from './routes/_authenticated/collections_.$id.attach'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PinterestCallbackRoute = PinterestCallbackRouteImport.update({
  id: '/pinterest/callback',
  path: '/pinterest/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSwitchProfileRoute =
  AuthenticatedSwitchProfileRouteImport.update({
    id: '/switch-profile',
    path: '/switch-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStorefrontRoute = AuthenticatedStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPinsRoute = AuthenticatedPinsRouteImport.update({
  id: '/pins',
  path: '/pins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsRoute = AuthenticatedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPinsPreviewRoute =
  AuthenticatedPinsPreviewRouteImport.update({
    id: '/pins_/preview',
    path: '/pins/preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPinsMonetizeBoardRoute =
  AuthenticatedPinsMonetizeBoardRouteImport.update({
    id: '/pins_/monetize-board',
    path: '/pins/monetize-board',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPinsCreateRoute = AuthenticatedPinsCreateRouteImport.update({
  id: '/pins_/create',
  path: '/pins/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPinsAttachRoute = AuthenticatedPinsAttachRouteImport.update({
  id: '/pins_/attach',
  path: '/pins/attach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsBrandIdRoute =
  AuthenticatedBrandsBrandIdRouteImport.update({
    id: '/brands_/$brandId',
    path: '/brands/$brandId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectionsIdAttachRoute =
  AuthenticatedCollectionsIdAttachRouteImport.update({
    id: '/collections_/$id/attach',
    path: '/collections/$id/attach',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pins': typeof AuthenticatedPinsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/storefront': typeof AuthenticatedStorefrontRoute
  '/switch-profile': typeof AuthenticatedSwitchProfileRoute
  '/pinterest/callback': typeof PinterestCallbackRoute
  '/s/$slug': typeof SSlugRoute
  '/brands/$brandId': typeof AuthenticatedBrandsBrandIdRoute
  '/pins/attach': typeof AuthenticatedPinsAttachRoute
  '/pins/create': typeof AuthenticatedPinsCreateRoute
  '/pins/monetize-board': typeof AuthenticatedPinsMonetizeBoardRoute
  '/pins/preview': typeof AuthenticatedPinsPreviewRoute
  '/collections/$id/attach': typeof AuthenticatedCollectionsIdAttachRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pins': typeof AuthenticatedPinsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/storefront': typeof AuthenticatedStorefrontRoute
  '/switch-profile': typeof AuthenticatedSwitchProfileRoute
  '/pinterest/callback': typeof PinterestCallbackRoute
  '/s/$slug': typeof SSlugRoute
  '/brands/$brandId': typeof AuthenticatedBrandsBrandIdRoute
  '/pins/attach': typeof AuthenticatedPinsAttachRoute
  '/pins/create': typeof AuthenticatedPinsCreateRoute
  '/pins/monetize-board': typeof AuthenticatedPinsMonetizeBoardRoute
  '/pins/preview': typeof AuthenticatedPinsPreviewRoute
  '/collections/$id/attach': typeof AuthenticatedCollectionsIdAttachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/brands': typeof AuthenticatedBrandsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pins': typeof AuthenticatedPinsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/storefront': typeof AuthenticatedStorefrontRoute
  '/_authenticated/switch-profile': typeof AuthenticatedSwitchProfileRoute
  '/pinterest/callback': typeof PinterestCallbackRoute
  '/s/$slug': typeof SSlugRoute
  '/_authenticated/brands_/$brandId': typeof AuthenticatedBrandsBrandIdRoute
  '/_authenticated/pins_/attach': typeof AuthenticatedPinsAttachRoute
  '/_authenticated/pins_/create': typeof AuthenticatedPinsCreateRoute
  '/_authenticated/pins_/monetize-board': typeof AuthenticatedPinsMonetizeBoardRoute
  '/_authenticated/pins_/preview': typeof AuthenticatedPinsPreviewRoute
  '/_authenticated/collections_/$id/attach': typeof AuthenticatedCollectionsIdAttachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/analytics'
    | '/brands'
    | '/dashboard'
    | '/onboarding'
    | '/pins'
    | '/profile'
    | '/settings'
    | '/storefront'
    | '/switch-profile'
    | '/pinterest/callback'
    | '/s/$slug'
    | '/brands/$brandId'
    | '/pins/attach'
    | '/pins/create'
    | '/pins/monetize-board'
    | '/pins/preview'
    | '/collections/$id/attach'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/analytics'
    | '/brands'
    | '/dashboard'
    | '/onboarding'
    | '/pins'
    | '/profile'
    | '/settings'
    | '/storefront'
    | '/switch-profile'
    | '/pinterest/callback'
    | '/s/$slug'
    | '/brands/$brandId'
    | '/pins/attach'
    | '/pins/create'
    | '/pins/monetize-board'
    | '/pins/preview'
    | '/collections/$id/attach'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/_authenticated/analytics'
    | '/_authenticated/brands'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/pins'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/storefront'
    | '/_authenticated/switch-profile'
    | '/pinterest/callback'
    | '/s/$slug'
    | '/_authenticated/brands_/$brandId'
    | '/_authenticated/pins_/attach'
    | '/_authenticated/pins_/create'
    | '/_authenticated/pins_/monetize-board'
    | '/_authenticated/pins_/preview'
    | '/_authenticated/collections_/$id/attach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  PinterestCallbackRoute: typeof PinterestCallbackRoute
  SSlugRoute: typeof SSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pinterest/callback': {
      id: '/pinterest/callback'
      path: '/pinterest/callback'
      fullPath: '/pinterest/callback'
      preLoaderRoute: typeof PinterestCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/switch-profile': {
      id: '/_authenticated/switch-profile'
      path: '/switch-profile'
      fullPath: '/switch-profile'
      preLoaderRoute: typeof AuthenticatedSwitchProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storefront': {
      id: '/_authenticated/storefront'
      path: '/storefront'
      fullPath: '/storefront'
      preLoaderRoute: typeof AuthenticatedStorefrontRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pins': {
      id: '/_authenticated/pins'
      path: '/pins'
      fullPath: '/pins'
      preLoaderRoute: typeof AuthenticatedPinsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands': {
      id: '/_authenticated/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pins_/preview': {
      id: '/_authenticated/pins_/preview'
      path: '/pins/preview'
      fullPath: '/pins/preview'
      preLoaderRoute: typeof AuthenticatedPinsPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pins_/monetize-board': {
      id: '/_authenticated/pins_/monetize-board'
      path: '/pins/monetize-board'
      fullPath: '/pins/monetize-board'
      preLoaderRoute: typeof AuthenticatedPinsMonetizeBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pins_/create': {
      id: '/_authenticated/pins_/create'
      path: '/pins/create'
      fullPath: '/pins/create'
      preLoaderRoute: typeof AuthenticatedPinsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pins_/attach': {
      id: '/_authenticated/pins_/attach'
      path: '/pins/attach'
      fullPath: '/pins/attach'
      preLoaderRoute: typeof AuthenticatedPinsAttachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands_/$brandId': {
      id: '/_authenticated/brands_/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof AuthenticatedBrandsBrandIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections_/$id/attach': {
      id: '/_authenticated/collections_/$id/attach'
      path: '/collections/$id/attach'
      fullPath: '/collections/$id/attach'
      preLoaderRoute: typeof AuthenticatedCollectionsIdAttachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBrandsRoute: typeof AuthenticatedBrandsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPinsRoute: typeof AuthenticatedPinsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStorefrontRoute: typeof AuthenticatedStorefrontRoute
  AuthenticatedSwitchProfileRoute: typeof AuthenticatedSwitchProfileRoute
  AuthenticatedBrandsBrandIdRoute: typeof AuthenticatedBrandsBrandIdRoute
  AuthenticatedPinsAttachRoute: typeof AuthenticatedPinsAttachRoute
  AuthenticatedPinsCreateRoute: typeof AuthenticatedPinsCreateRoute
  AuthenticatedPinsMonetizeBoardRoute: typeof AuthenticatedPinsMonetizeBoardRoute
  AuthenticatedPinsPreviewRoute: typeof AuthenticatedPinsPreviewRoute
  AuthenticatedCollectionsIdAttachRoute: typeof AuthenticatedCollectionsIdAttachRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBrandsRoute: AuthenticatedBrandsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPinsRoute: AuthenticatedPinsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStorefrontRoute: AuthenticatedStorefrontRoute,
  AuthenticatedSwitchProfileRoute: AuthenticatedSwitchProfileRoute,
  AuthenticatedBrandsBrandIdRoute: AuthenticatedBrandsBrandIdRoute,
  AuthenticatedPinsAttachRoute: AuthenticatedPinsAttachRoute,
  AuthenticatedPinsCreateRoute: AuthenticatedPinsCreateRoute,
  AuthenticatedPinsMonetizeBoardRoute: AuthenticatedPinsMonetizeBoardRoute,
  AuthenticatedPinsPreviewRoute: AuthenticatedPinsPreviewRoute,
  AuthenticatedCollectionsIdAttachRoute: AuthenticatedCollectionsIdAttachRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  PinterestCallbackRoute: PinterestCallbackRoute,
  SSlugRoute: SSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
