// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { withConnectRetry } from "@/lib/resilient-fetch";
import { verifyTokenLocal } from "./token-verifier";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

// Every Supabase call this client makes — including the JWKS fetch inside
// `auth.getClaims()` — goes through this fetch. `withConnectRetry` wraps the
// real fetch with a single retry for a transient connect-level failure
// (UND_ERR_CONNECT_TIMEOUT and siblings) — see src/lib/resilient-fetch.ts
// for why that error is a local-process condition, not a Supabase outage.
const resilientFetch = withConnectRetry("supabase.auth_middleware");

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return resilientFetch(input, { ...init, headers });
  };
}

// A single, process-wide client used ONLY to verify tokens via getClaims. A
// fresh client re-fetches the signing keys (JWKS) over the network on its very
// first getClaims call; creating one per request therefore made EVERY request
// depend on a live JWKS fetch (and turned a brief connect-timeout into a hard
// 401). Reusing one client caches the JWKS in-process after the first fetch,
// so subsequent requests verify locally with no network at all. It carries no
// per-user Authorization header — getClaims verifies the token passed to it.
let verifierClient: ReturnType<typeof createClient<Database>> | null = null;
function getVerifierClient(url: string, key: string) {
  if (!verifierClient) {
    verifierClient = createClient<Database>(url, key, {
      global: { fetch: createSupabaseFetch(key) },
      auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
    });
  }
  return verifierClient;
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    if (token.split(".").length !== 3) {
      throw new Error("Unauthorized: Invalid token");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    // Fast path: verify the token locally against the JWKS that was warmed at
    // boot — no network call, so this succeeds on the first try. Falls through
    // to Supabase's authoritative getClaims for anything it can't positively
    // verify (cold cache, rotated/unknown key, non-ES256 token).
    const local = await verifyTokenLocal(token);
    if (local?.sub) {
      return next({
        context: {
          supabase,
          userId: local.sub,
          claims: local,
        },
      });
    }

    // Fallback: verify through the shared client so the JWKS is fetched once
    // per process and cached, instead of a fresh network fetch on every request.
    const verifier = getVerifierClient(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!);
    const { data, error } = await verifier.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
